
//--->>Types for Login---->>>
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_REQUESTING = 'LOGIN_USER_REQUESTING';

//--->>Types for SignUp---->>>
export const SIGN_UP_REQUESTING = 'SIGN_UP_REQUESTING';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

//--->>Types for Forgot password---->>>
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_REQUESTING = 'FORGOT_PASSWORD_REQUESTING';




//--->>Types for LoginUser & Info---->>>
export const CHANGE_EMAIL_REQUEST = 'CHANGE_EMAIL_REQUEST';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_PASSWORD_REQUEST = 'VERIFY_PASSWORD_REQUEST';
export const VERIFY_PASSWORD_STATUS = 'VERIFY_PASSWORD_STATUS';
export const CHANGE_PASSWORD_DONE = 'CHANGE_PASSWORD_DONE';
export const CHANGE_EMAIL_DONE = 'CHANGE_EMAIL_DONE';

//--->>Types for Logout---->>>
export const LOGOUT_USER_REQUESTING = "LOGOUT_USER_REQUESTING";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

